### ISSUE TITLE
TMPDIR gets lost

### ISSUE THREAD

**Issue by tbg** [benesch/autouseradd#2]
Over at CRDB we noticed that `./build/builder.sh` loses the TMPDIR passed to docker run (via `--env=TMPDIR=/go/..../artifacts`) and narrowed it down to `autouseradd`.

**Comment by tbg** [comment]
(Other env vars, however, are passed through just fine)

**Comment by benesch** [comment]
This is a glibc "feature" :/ 

https://bugzilla.redhat.com/show_bug.cgi?id=129682#c1

**Comment by benesch** [comment]
Easy enough to work around though. I’ll have a patch out early afternoon EST.

**Comment by benesch** [comment]
Fixed in #3. Thanks for the report!
